ASP.NET Core Web Application/projetoCDH/projetoCDH/Controllers/HorarioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using projetoCDH.BLL.LoginAuth;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace projetoCDH.Controllers
{
    public class HorarioController : Controller
    {
        public Someone FromJsonSomeone
        {
            get => HttpContext.Session.GetString("objJSONUsuario") == null ? SomeoneNotFound.Someone : JsonConvert.DeserializeObject<Someone>(HttpContext.Session.GetString("objJSONUsuario"));
        }
        [HttpGet("/planofuncionamento")]
        public ActionResult PlanoFuncView()
        {
            return View(new projetoCDH.ViewModel.ViewForModel(FromJsonSomeone));
            //return View("PlanoFuncView");
        }

    }
}

ASP.NET Core Web Application/projetoCDH/projetoCDH/Controllers/RetornadoresJSONFormadorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using projetoCDH.BLL.LoginAuth;
using projetoCDH.Excelconf;
using projetoCDH.Forms;
using projetoCDH.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace projetoCDH.Controllers
{
    public class RetornadoresJSONFormadorController : Controller
    {
        public Someone FromJsonSomeone
        {
            get => HttpContext.Session.GetString("objJSONUsuario") == null ? SomeoneNotFound.Someone : JsonConvert.DeserializeObject<Someone>(HttpContext.Session.GetString("objJSONUsuario"));
        }
        public class NaoRepeteNomeFormador : IEqualityComparer<Notificacao>
        {
            public bool Equals(Notificacao x, Notificacao y)
            {
                return x.IdFormador == y.IdFormador;
            }

            public int GetHashCode(Notificacao obj)
            {
                return obj.IdFormador.GetHashCode();
            }
        }


        public class TurmaRelacionada : IEqualityComparer<TurmaRelacionada>
        {
            public int IdNotificacao { get; set; }
            public DateTime HoraCriada { get; set; }
            public string NomeTurma { get; set; }
            public string NomeFormador { get; set; }
            public bool NotificacaoInserida { get; set; }
            public string PathExcel { get; set; }
            //pega o nome das turmas e dos formadores que estão associados a notificacao
            public static IEnumerable<TurmaRelacionada> Get(int id)
            {

                using (ModelCDHContext mcdh = new ModelCDHContext())
                {
                    return (from noti in mcdh.Notificacao
                            join fm in mcdh?.Formador on noti.IdFormador equals fm.Id
                            where noti.IdFormador == id
                            select new TurmaRelacionada
                            {
                                HoraCriada = noti.HoraCriada,
                                IdNotificacao = noti.Id,
                                NomeTurma = noti.Turma,
                                NomeFormador = fm.Nome,
                                NotificacaoInserida = noti.Inserido,
                                PathExcel = noti.PathExcel
                            }).ToList().Distinct(new TurmaRelacionada());
                }
            }

            public bool Equals(TurmaRelacionada x, TurmaRelacionada y)
            {
                return x.NomeTurma == y.NomeTurma;
            }

            public int GetHashCode(TurmaRelacionada obj)
            {
                return obj.NomeTurma.GetHashCode();
            }
        }

        public static IEnumerable<Notificacao> NotificacoesPQuery { get; set; }
        public static IEnumerable<Turma> TurmasPQuery { get; set; }


        [Route("/RetornaJsonHistorico")]
        public ActionResult RetornaJsonHistorico()
        {
            List<object> objAnonimo = new List<object>();
            string makeAction = "";

            Someone sm = HttpContext.Session.GetString("objJSONUsuario") == null ? SomeoneNotFound.Someone : JsonConvert.DeserializeObject<Someone>(HttpContext.Session.GetString("objJSONUsuario"));

            IEnumerable<Notificacao> listaNotificacoes = NotificacoesPQuery.ToList().Where(x => x.IdFormador == sm.Formador.Id);

            IEnumerable<TurmaRelacionada> tmr = TurmaRelacionada.Get(sm.Formador.Id);
            foreach (TurmaRelacionada not in tmr)
            {
                Regime rgm = new Regime();
                using (ModelCDHContext mcdh = new ModelCDHContext())
                {

                    Turma tma = mcdh.Turma.FirstOrDefault(x => x.Nome == not.NomeTurma);

                    rgm = mcdh.Regime.FirstOrDefault(x => x.Id == tma.IdRegime);
                    var tesdste = tma.IdRegimeNavigation.NomeRegime;

                }
                makeAction = (not.NotificacaoInserida) ?
                    $"<div class=\"btn btn-success btn-circle\"><i class=\"fas fa-check\"></i></div>" : $"<a class=\"btn btn-dark btn-circle\" style=\"cursor: pointer;\"onclick=\"BaixaExcel({not.IdNotificacao},\'{not.PathExcel}\')\"><i class=\"fa fa-arrow-down\" style=\"color:white\"aria-hidden=\"true\"></i></a>";

                //var s = String.Format(new System.Globalization.CultureInfo("pt-PT"), "{0:f}", not?.HoraCriada ?? DateTime.Now);
                objAnonimo.Add(new
                {
                    Id = not?.IdNotificacao ?? 0,
                    NomeTurma = not?.NomeTurma ?? "zero",
                    HoraCriada = String.Format(new System.Globalization.CultureInfo("pt-PT"), "{0:F}", not?.HoraCriada) ?? "No Time",
                    NomeRegime = rgm.NomeRegime ?? "Sem regime",
                    Status = makeAction
                });
            }
            return new JsonResult(objAnonimo);
        }

        [Route("/RetornaJsonHorarios")]
        public ActionResult RetornaJsonHorarios()
        {
            List<object> objAnonimo = new List<object>();
            string makeAction = "";

            Someone sm = HttpContext.Session.GetString("objJSONUsuario") == null ? SomeoneNotFound.Someone : JsonConvert.DeserializeObject<Someone>(HttpContext.Session.GetString("objJSONUsuario"));

            IEnumerable<Notificacao> listaNotificacoes = NotificacoesPQuery.ToList().Where(x => x.IdFormador == sm.Formador.Id);

            IEnumerable<TurmaRelacionada> tmr = TurmaRelacionada.Get(sm.Formador.Id);
            foreach (TurmaRelacionada not in tmr)
            {

                if (not.NotificacaoInserida == false)
                {
                    Regime rgm = new Regime();
                    using (ModelCDHContext mcdh = new ModelCDHContext())
                    {

                        Turma tma = mcdh.Turma.FirstOrDefault(x => x.Nome == not.NomeTurma);

                        rgm = mcdh.Regime.FirstOrDefault(x => x.Id == tma.IdRegime);
                        var tesdste = tma.IdRegimeNavigation.NomeRegime;

                    }
                    makeAction = $"<a style=\"color:white; background:#ff12a9;border-color:gray; cursor:pointer;\"" +
                        $"class=\"btn btn-primary btn-circle\" data-toggle=\"modal\" data-target=\"#uploadModal\" " +
                        $"data-idnotificacao=\"{not.IdNotificacao}\" data-nometurma=\"{not.NomeTurma}\"><i class=\"fa fa-upload\" aria-hidden=\"true\"></i></a>";

                    //var s = String.Format(new System.Globalization.CultureInfo("pt-PT"), "{0:f}", not?.HoraCriada ?? DateTime.Now);
                    objAnonimo.Add(new
                    {
                        Id = not?.IdNotificacao ?? 0,
                        NomeTurma = not?.NomeTurma ?? "zero",
                        HoraCriada = String.Format(new System.Globalization.CultureInfo("pt-PT"), "{0:F}", not?.HoraCriada) ?? "No Time",
                        NomeRegime = rgm.NomeRegime ?? "Sem regime",
                        Status = makeAction
                    });
                }
            }
            return new JsonResult(objAnonimo);
        }

        [Route("/RetornaJSONTurma")]
        public ActionResult RetornaJSONTurma()
        {
            List<object> objAnonimo = new List<object>();

            using (ModelCDHContext mcdh = new ModelCDHContext())
            {
                List<Regime> regimes = new List<Regime>();
                List<Curso> cursos = new List<Curso>();
                IEnumerable<Turma> tmas = mcdh.Turma.ToList();
                regimes = mcdh.Regime.ToList();
                cursos = mcdh.Curso.ToList();

                foreach (var tm in tmas)
                {
                    //string situacao = $"<a style=\"color:white; background:#5a5c69; cursor:pointer;\"" +
                    //     $"class=\"btn btn-primary btn-circle\" data-toggle=\"modal\" data-target=\"#situacaoModal\" " +
                    //     $"data-idregime=\"{tm.IdRegime}\"><i class=\"fa fa-upload\" aria-hidden=\"true\"></i></a>";

                    string situacao = $"<button type=\"button\" class=\"btn btn-outline-primary\" data-idregime=\"{tm.IdRegime}\" data-idcurso=\"{tm.IdCurso}\"data-toggle=\"modal\" style=\"width:123px\" data-target=\"#situacaoModal\">Situação</button>";

                    Regime nomeRegime = regimes.FirstOrDefault(x => x.Id == tm?.IdRegime);
                    Curso nomeCurso = cursos.FirstOrDefault(x => x.Id == tm?.IdCurso);
                    objAnonimo.Add(new
                    {
                        Id = tm.Id,
                        Nome = tm.Nome,
                        NomeRegime = nomeRegime.NomeRegime,
                        NomeCurso = nomeCurso.Nome,
                        DataInicio = String.Format(new System.Globalization.CultureInfo("pt-PT"), "{0:dd/MM/yyyy}", tm?.DataInicio) ?? "No Time",
                        Coordenador = tm.Coordenador,
                        Situacao = situacao 
                    });
                }
            }
            return new JsonResult(objAnonimo);
        }

        [Route("/RetornaFormadoresQueFaltamMandarHorariosDeUmaDeterminadaTurma")]
        public ActionResult RetornaFormadoresQueFaltamMandarHorariosDeUmaDeterminadaTurma(string idTurma)
        {
            List<Formador> formadores = new List<Formador>();
            List<object> objAnonimo = new List<object>();

            using (ModelCDHContext mcdh = new ModelCDHContext())
            {
                Turma tm = mcdh.Turma.FirstOrDefault(x => x.Id == int.Parse(idTurma));
                IEnumerable<Notificacao> ntf = mcdh.Notificacao.Where(x => x.Turma == tm.Nome).ToList()/*.Distinct(new NaoRepeteNomeFormador())*/;
                List<Formador> fmdres = mcdh.Formador.ToList();

                foreach (var item in ntf)
                {

ASP.NET Core Web Application/projetoCDH/projetoCDH/Views/MainPage/CriarCurso.cshtml
@model ViewForModel
@{
    ViewData["Title"] = "Criar Curso";
}


@section ImportsHead{
    <script src="~/Templates/PrincipalPage/dashadm/vendor/jquery/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
}
<!-- Begin Page Content -->
<div class="container-fluid">

    <div class="container">

        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Criação do curso</h1>
        </div>

        <!-- Circle Buttons -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Introduza o nome do curso</h6>
            </div>
            <div class="card-body">
                <form>
                    <div class="form-group">
                        <label>Nome</label>
                        <input class="form-control" id="nomeCurso" onkeyup="ChangingName(this); FormandoSigla(this);" placeholder="Nome do curso" required maxlength="60">
                        <div class="valid-feedback">
                            Nome disponível!
                        </div>
                        <div class="invalid-feedback">
                            Nome já existe!
                        </div>
                    </div>


                    <div class="alert alert-primary" role="alert" id="tipoSigla" style="width: 30%; padding: 8px; display:block; display:inline; margin-top: 5px;">
                        <strong>Sigla:</strong> <label style="padding: 0px; margin: 0px" for="tipoSigla" id="siglaTexto">(A sigla aparecerá aqui)</label>
                    </div>

                    <div class="form-group" style="margin-top:18px">
                        <label>Horas</label>
                        <input class="form-control" id="horasCurso" onkeyup="ChangingHours(this);" placeholder="Número total de horas" required maxlength="5">
                        <div class="valid-feedback">
                            Horas válidas!
                        </div>
                        <div class="invalid-feedback">
                            Horas inválidas!
                        </div>
                    </div>





                </form>
                <button id="submeter" class="btn btn-primary" style="float:right">Submeter</button>
            </div>
        </div>
    </div>
</div>
<footer class="sticky-footer bg-white  text-center"
        style="
        bottom: 0;
        position: fixed;
        width: 100%;
        ">
    <div class="container my-auto">
        <div class="copyright my-auto">
            <span style="margin-right:10%;">Copyright © Your Website 2019</span>
        </div>
    </div>
</footer>
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>


<script>
    let boolChangedName;
    let boolChangedHours;

    let objCurso = {
        Id: -1,
        Nome: "Nome",
        Sigla: "Sigla",
        TotalHoras: 0
    };


    $(function () {
        $("#submeter").attr("disabled", true);
    });

    $("#submeter").click(function () {

        Swal.fire({
            title: 'Deseja criar um curso?',
            text: `Nome: ${objCurso.Nome}, Sigla: ${objCurso.Sigla}`,
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sim, Crie!',
            cancelButtonText: 'Não, Cancele!',
        }).then((result) => {
            if (result.value) {
                $.ajax({
                    method: "POST",
                    url: "/InserirCurso",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    data: JSON.stringify(objCurso),
                    success: function (data) {
                        Swal.fire({
                            position: 'center',
                            type: 'success',
                            title: 'Curso criado!',
                            showConfirmButton: false,
                            timer: 1500
                        });
                        setTimeout(function () {
                            location.reload()
                        }, 1600);
                        console.log(data);
                    },
                    error: function (data) {
                        console.log(data);
                    }
                });
            }
        });
    });



    function FormandoSigla(othis) {
        let arrSigla = othis.value.split(" ");
        let arrSiglaFeito = [];
        arrSigla.forEach(function (item, index) {

            if (item != "da" && item != "de" && item != "de" && item != "do" && item != "du" && item != "e")
                arrSiglaFeito.push(item[0]);
        });
        $("#siglaTexto").text(arrSiglaFeito.join(""));
    }

    function ChangingName(othis) {

        objCurso.Nome = othis.value;
        objCurso.Sigla = $("#siglaTexto").text();
        if (/\w* \w+ ?[a-zA-Z0-9_ ]*\w/g.test(othis.value)) {
            $.ajax({
                method: "POST",
                url: "/RetornaTrueSeNomeCursoIgual",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: JSON.stringify(objCurso),
                success: function (data) {
                    if (data) {
                        boolChangedName = false;
                        $("#nomeCurso").addClass("is-invalid");
                        $("#nomeCurso").removeClass("is-valid");
                        $("#submeter").attr("disabled", true);
                    }
                    else {
                        boolChangedName = true;
                        $("#submeter").attr("disabled", false);
                        $("#nomeCurso").addClass("is-valid");
                        $("#nomeCurso").removeClass("is-invalid");
                    }
                    ValidaTudo();
                    console.log(data);
                },
                error: function (data) {
                    console.log(data);
                }
            });
        }
        else {
            boolChangedName = false;
            $("#submeter").attr("disabled", true);
            $("#nomeCurso").removeClass("is-invalid");
            $("#nomeCurso").removeClass("is-valid");
            ValidaTudo();
        }
    }
    function ChangingHours(othis) {
        if (/^[0-9]*$/g.test(othis.value)) {
            objCurso.TotalHoras = parseInt(othis.value);
            boolChangedHours = true;
            $("#horasCurso").addClass("is-valid");
            $("#horasCurso").removeClass("is-invalid");
        } else {
            boolChangedHours = false;
            $("#horasCurso").addClass("is-invalid");
            $("#horasCurso").removeClass("is-valid");
        }
        ValidaTudo();
    }

    function ValidaTudo() {
        if (boolChangedHours && boolChangedName)
            $("#submeter").attr("disabled", false);
        else {
            $("#submeter").attr("disabled", true);
        }
    }

</script>

ASP.NET Core Web Application/projetoCDH/projetoCDH/Views/MainPage/Horarios.cshtml
@model ViewForModel

@{
    ViewData["Title"] = "Horários";
}

@section ImportsHead{
<link href="~/Templates/PrincipalPage/dashadm/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
}

<script>
    function ValidaUpload() {
        if ($("#fileInput").val() == '') {
            $("#uploadButton").attr('disabled', true);
        }
        else {
            $("#uploadButton").attr('disabled', false);
        }
    }
</script>

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Seção destinada a<strong> envio de disponibilidades</strong> </h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Horários</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" style="text-align:center" id="Horarios" width="100%" cellspacing="0"></table>
            </div>

            <div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="uploadModalLabel">Id: </h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form asp-action="UploadaExcel" asp-controller="RetornadoresJSONFormador" method="post" enctype="multipart/form-data" id="formInsereHorario">
                            <div class="modal-body">
                                <div class="form-group">
                                    <label asp-for="@Model.UploadFileExcel.IdNotificacao" class="col-form-label" hidden>Id</label>
                                    <input asp-for="@Model.UploadFileExcel.IdNotificacao" class="form-control" id="recipient-idNotificacao" hidden>
                                </div>
                                <div class="form-group">
                                    <label asp-for="@Model.UploadFileExcel.NomeTurma" class="col-form-label " hidden>Nome da turma:</label>
                                    <input asp-for="@Model.UploadFileExcel.NomeTurma" class="form-control" id="recipient-name" hidden>
                                </div>


                                <div class="form-group" style="text-align:left;">
                                    <label asp-for="UploadFileExcel.FileExcel" class="col-form-label alert alert-success"></label>
                                    <input id="fileInput" asp-for="UploadFileExcel.FileExcel" onchange="ValidaUpload();" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" />
                                </div>


                            </div>
                            <div class="modal-footer">
                                <input type="submit" class="btn btn-primary" id="uploadButton" value="Upload" onclick="" />
                            </div>
                        </form>
                        @*<div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>*@
                            @*<button type="submit" class="btn btn-primary">Send message</button>
                        </div>*@
                    </div>
                </div>
            </div>

        </div>

    </div>


</div>

<script>
    $('#uploadModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget); // Button that triggered the modal
        var idnot = button.data('idnotificacao'); // Extract info from data-* attributes
        var nomenot = button.data('nometurma'); // Extract info from data-* attributes
        $("#uploadModalLabel").html(`ID - ${idnot}`);
        $("#recipient-name").val(nomenot);
        $("#recipient-idNotificacao").val(idnot);

        $(".alert-success").html(`Insira o horário em Excel da turma <strong> ${nomenot}</strong>`);


        //var modal = $(this);
        //modal.find('.modal-title').text('New message to ' + recipient);
        //modal.find('.modal-body input').val(recipient);
        //modal.find('#idNotificacao').val(recipient);
    })




</script>
<!-- Bootstrap core JavaScript-->
<script src="~/Templates/PrincipalPage/dashadm/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="~/Templates/PrincipalPage/dashadm/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
@*
<script src="~/Templates/PrincipalPage/dashadm/js/sb-admin-2.min.js"></script>*@

<!-- Page level plugins -->
<script src="~/Templates/PrincipalPage/dashadm/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="~/Templates/PrincipalPage/dashadm/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="~/Templates/PrincipalPage/dashadm/js/demo/datatables-demo.js"></script>



<!-- Button trigger modal -->






<script>

    $(function () {
        $("#uploadButton").attr('disabled', true);
    });



    $('#Horarios').dataTable({
        processing: true,
        order: [
            [0, 'desc']
        ],
        ajax: {
            url: "/RetornaJsonHorarios",
            dataSrc: ''
        },
        //data: data,
        columns: [
            {
                "title": "Id",
                "data": "id"
            },
            {
                "title": "Nome da Turma",
                "data": "nomeTurma"
            },
            {
                "title": "Data de Criação",
                "data": "horaCriada"
            },
            {
                "title": "Regime",
                "data": "nomeRegime"
            },
            {
                "title": "Upload",
                "data": "status"
            }
        ]
    });


    $("#uploadButton").click(function (e) {
        e.preventDefault();
        var nomenot = $("#recipient-name").val(); // Extract info from data-* attributes
        Swal.fire({
            title: 'Deseja enviar?',
            text: `Sua disponibilidade será enviada para a turma "${nomenot}" `,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sim, envie!',
            cancelButtonText: 'Não, cancele'
        }).then((result) => {
            if (result.value) {
                Swal.fire({
                    position: 'center',
                    icon: 'success',
                    title: 'Enviado',
                    showConfirmButton: false,
                    timer: 1500
                })
                $("#formInsereHorario").submit();
                //var promise = new Promise(function (resolve, reject) {
                //    window.setTimeout(function () {
                //        resolve(true);
                //    }, 3000);
                //});
                return true;
            }
            else {
                return false;
            }
        })
    });

</script>

ASP.NET Core Web Application/projetoCDH/projetoCDH/Views/MainPage/TurmaAssociada.cshtml
@model ViewForModel

@{
    ViewData["Title"] = "Turmas Associada";
}

@section ImportsHead{
    <link href="~/Templates/PrincipalPage/dashadm/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
}

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Seção destinada a<strong> consulta de envio de horários</strong> </h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Histórico</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" style="text-align:center" id="TurmaAssociada" width="100%" cellspacing="0">
                </table>
            </div>
        </div>
    </div>

</div>
<!-- Bootstrap core JavaScript-->
<script src="~/Templates/PrincipalPage/dashadm/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="~/Templates/PrincipalPage/dashadm/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
@*<script src="~/Templates/PrincipalPage/dashadm/js/sb-admin-2.min.js"></script>*@

<!-- Page level plugins -->
<script src="~/Templates/PrincipalPage/dashadm/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="~/Templates/PrincipalPage/dashadm/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="~/Templates/PrincipalPage/dashadm/js/demo/datatables-demo.js"></script>

<script>
    $('#TurmaAssociada').dataTable({
        processing: true,
        order: [
            [0, 'desc']
        ],
        ajax: {
            url: "/RetornaJsonHistorico",
            dataSrc: ''
        },
        //data: data,
        columns: [
            {
                "title": "Id",
                "data": "id"
            },
            {
                "title": "Nome da Turma",
                "data": "nomeTurma"
            },
            {
                "title": "Data de Criação",
                "data": "horaCriada"
            },
            {
                "title": "Regime",
                "data": "nomeRegime"
            },
            {
                "title": "Status",
                "data": "status"
            }
        ]
    });

</script>